# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.core.indexer import indexer_pb2 as indexer__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in indexer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IndexerStub:
    """Repository indexing: file walk plus tree-sitter parsing, extracted from the Python API.

    WHY A SEPARATE SERVICE, STATED HONESTLY
    Not for parse throughput. Measured on this repository, ThreadPoolExecutor over the
    Python parser gives 1.02x (py-tree-sitter never releases the GIL) and
    ProcessPoolExecutor gives 2.84x, while only ~41% of the parse phase is actually C -- so
    a perfect native rewrite ceilings around 2.4x, below what a half-day change to the
    existing Python already achieves.

    The real reason is a process and failure boundary. repos.py runs indexing by spinning a
    new event loop inside an anyio threadpool thread and blocking it for minutes, in the
    same process that serves chat. This moves that CPU-bound, GIL-bound, minutes-long stage
    behind an explicit contract.

    Server streaming is the point of using gRPC here rather than one big response: progress
    becomes part of the contract instead of shared mutable state, which is the same bug
    class that made the SSE progress bar show only 0% or 100%.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IndexRepo = channel.unary_stream(
                '/codebaseqa.indexer.v1.Indexer/IndexRepo',
                request_serializer=indexer__pb2.IndexRequest.SerializeToString,
                response_deserializer=indexer__pb2.IndexEvent.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/codebaseqa.indexer.v1.Indexer/Health',
                request_serializer=indexer__pb2.HealthRequest.SerializeToString,
                response_deserializer=indexer__pb2.HealthResponse.FromString,
                _registered_method=True)


class IndexerServicer:
    """Repository indexing: file walk plus tree-sitter parsing, extracted from the Python API.

    WHY A SEPARATE SERVICE, STATED HONESTLY
    Not for parse throughput. Measured on this repository, ThreadPoolExecutor over the
    Python parser gives 1.02x (py-tree-sitter never releases the GIL) and
    ProcessPoolExecutor gives 2.84x, while only ~41% of the parse phase is actually C -- so
    a perfect native rewrite ceilings around 2.4x, below what a half-day change to the
    existing Python already achieves.

    The real reason is a process and failure boundary. repos.py runs indexing by spinning a
    new event loop inside an anyio threadpool thread and blocking it for minutes, in the
    same process that serves chat. This moves that CPU-bound, GIL-bound, minutes-long stage
    behind an explicit contract.

    Server streaming is the point of using gRPC here rather than one big response: progress
    becomes part of the contract instead of shared mutable state, which is the same bug
    class that made the SSE progress bar show only 0% or 100%.
    """

    def IndexRepo(self, request, context):
        """Walk and parse a checkout, streaming progress and chunk batches as they are produced.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Cheap liveness probe. Returns the grammars this build actually links, which is not
        guaranteed to match the Python side -- see ParserInfo.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IndexerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IndexRepo': grpc.unary_stream_rpc_method_handler(
                    servicer.IndexRepo,
                    request_deserializer=indexer__pb2.IndexRequest.FromString,
                    response_serializer=indexer__pb2.IndexEvent.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=indexer__pb2.HealthRequest.FromString,
                    response_serializer=indexer__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'codebaseqa.indexer.v1.Indexer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('codebaseqa.indexer.v1.Indexer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Indexer:
    """Repository indexing: file walk plus tree-sitter parsing, extracted from the Python API.

    WHY A SEPARATE SERVICE, STATED HONESTLY
    Not for parse throughput. Measured on this repository, ThreadPoolExecutor over the
    Python parser gives 1.02x (py-tree-sitter never releases the GIL) and
    ProcessPoolExecutor gives 2.84x, while only ~41% of the parse phase is actually C -- so
    a perfect native rewrite ceilings around 2.4x, below what a half-day change to the
    existing Python already achieves.

    The real reason is a process and failure boundary. repos.py runs indexing by spinning a
    new event loop inside an anyio threadpool thread and blocking it for minutes, in the
    same process that serves chat. This moves that CPU-bound, GIL-bound, minutes-long stage
    behind an explicit contract.

    Server streaming is the point of using gRPC here rather than one big response: progress
    becomes part of the contract instead of shared mutable state, which is the same bug
    class that made the SSE progress bar show only 0% or 100%.
    """

    @staticmethod
    def IndexRepo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/codebaseqa.indexer.v1.Indexer/IndexRepo',
            indexer__pb2.IndexRequest.SerializeToString,
            indexer__pb2.IndexEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codebaseqa.indexer.v1.Indexer/Health',
            indexer__pb2.HealthRequest.SerializeToString,
            indexer__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
